# Generated by Django 3.1.4 on 2021-01-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0002_auto_20210112_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgradedetermination',
            name='grade_components',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finalgradedetermination',
            name='grade_marks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finalgradedetermination',
            name='grade_notes',
            field=models.TextField(blank=True),
        ),
    ]
