# Generated by Django 3.1.4 on 2021-01-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0003_auto_20210112_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarinformation',
            name='course_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarinformation',
            name='course_credit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarinformation',
            name='course_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarinformation',
            name='course_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='content_complementarystudies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='content_engineeringdesign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='content_engineeringscience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='content_math',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='content_naturalscience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='lab_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='lab_safetyexaminer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='lab_safetytaught',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='lab_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='section_lab',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='section_lecture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='section_tutorial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
