# Generated by Django 3.1.4 on 2021-01-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0004_auto_20210112_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcomes',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
    ]
