# Generated by Django 3.1.4 on 2021-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0005_auto_20210112_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_name', models.CharField(max_length=100)),
                ('syllabus_number', models.IntegerField()),
            ],
        ),
    ]
